apiVersion: apps/v1
kind: Deployment
metadata:
  name: dgs-skeleton
  labels:
    app: dgs-skeleton
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dgs-skeleton
  template:
    metadata:
      labels:
        app: dgs-skeleton
    spec:
      imagePullSecrets:
        - name: artifactory-pull-secret
      containers:
      - name: dgs-skeleton
        image: CONTAINER_IMAGE
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /jfrog-demo/health/status
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /jfrog-demo/health/status
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: dgs-skeleton-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: dgs-skeleton
