apiVersion: apps/v1
kind: Deployment
metadata:
  name: dgs-skeleton
  labels:
    app: dgs-skeleton
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dgs-skeleton
  template:
    metadata:
      labels:
        app: dgs-skeleton
    spec:
      imagePullSecrets:
        - name: artifactory-pull-secret
      containers:
      - name: dgs-skeleton
        image: CONTAINER_IMAGE
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health/status
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/status
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: dgs-skeleton-service
spec:
  type: NodePort  # External access via node IP + port
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080  # Optional: specify port (30000-32767)
    protocol: TCP
  selector:
    app: dgs-skeleton
